# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://orion.mokpo.ac.kr:8382/uniformDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ScE1234**

  # Thymeleaf 캐시 비활성화
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

openai:
  api-key: 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
chatgpt:
  api-key: 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
